# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Update_Versions

on:
  push:
    branches: [master]
  repository_dispatch:
  schedule: #m h d m w 
    - cron: '0 5 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: run
    - uses: EndBug/add-and-commit@v9
      with:
        add: powernukkit-versions.json
        author_name: PowerNukkit Bot
        author_email: github-bot@powernukkit.org
        message: Update powernukkit-versions.json
        push: true
